# Generated by Django 2.1.1 on 2018-09-13 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoistureModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=8, verbose_name='Project number')),
                ('hole_id', models.CharField(max_length=8, verbose_name='Hole number')),
                ('depth_top', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Top depth (m)')),
                ('sample_type', models.CharField(max_length=4, verbose_name='Sample type')),
                ('technician', models.CharField(max_length=32, verbose_name='Technician name')),
            ],
        ),
    ]
