# Generated by Django 2.1.1 on 2018-09-19 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moisture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moisturemodel',
            name='balance',
            field=models.CharField(blank=True, choices=[('BAL-001', 'BAL-001'), ('BAL-003', 'BAL-003'), ('BAL-004', 'BAL-004'), ('BAL-005', 'BAL-005'), ('BAL-006', 'BAL-006'), ('BAL-007', 'BAL-007'), ('BAL-008', 'BAL-008'), ('BAL-009', 'BAL-009'), ('BAL-010', 'BAL-010')], max_length=7, verbose_name='Balance used'),
        ),
        migrations.AddField(
            model_name='moisturemodel',
            name='mc_con',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID'),
        ),
        migrations.AddField(
            model_name='moisturemodel',
            name='mc_con_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)'),
        ),
        migrations.AddField(
            model_name='moisturemodel',
            name='mc_dry1_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)'),
        ),
        migrations.AddField(
            model_name='moisturemodel',
            name='mc_dry2_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)'),
        ),
        migrations.AddField(
            model_name='moisturemodel',
            name='mc_method',
            field=models.CharField(choices=[('BS 1377 - 2 : 1990 3.2.3.1', 'Fine-grained Soil'), ('BS 1377 - 2 : 1990 3.2.3.2', 'Medium-grained Soil'), ('BS 1377 - 2 : 1990 3.2.3.3', 'Coarse-grained Soil')], default='BS 1377 - 2 : 1990 3.2.3.1', max_length=32, verbose_name='Test method'),
        ),
        migrations.AddField(
            model_name='moisturemodel',
            name='mc_wet_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)'),
        ),
        migrations.AddField(
            model_name='moisturemodel',
            name='oven',
            field=models.CharField(blank=True, choices=[('OVE-001', 'OVE-001'), ('OVE-002', 'OVE-002'), ('OVE-004', 'OVE-004'), ('OVE-005', 'OVE-005'), ('OVE-006', 'OVE-006')], max_length=7, verbose_name='Oven used'),
        ),
        migrations.AddField(
            model_name='moisturemodel',
            name='oven_temp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oven temperature (degrees celcius)'),
        ),
        migrations.AddField(
            model_name='moisturemodel',
            name='test_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
