# Generated by Django 2.1 on 2018-08-21 23:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atterberg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email_address', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=7)),
                ('project_name', models.CharField(max_length=128)),
                ('atterberg_test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='atterberg.AttModel')),
                ('engineer_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lab.Engineer')),
            ],
        ),
    ]
