# Generated by Django 2.1 on 2018-08-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='atterberg_test',
        ),
    ]
