# Generated by Django 2.1.1 on 2018-09-13 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=8, verbose_name='Project number')),
                ('hole_id', models.CharField(max_length=8, verbose_name='Hole number')),
                ('depth_top', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Top depth (m)')),
                ('sample_type', models.CharField(max_length=4, verbose_name='Sample type')),
                ('technician', models.CharField(max_length=32, verbose_name='Technician name')),
                ('att_method', models.CharField(choices=[('4.3', '4 Point (Definitive)'), ('4.4', '1 Point')], default='4.3', max_length=3, verbose_name='Test method')),
                ('check_cal', models.BooleanField(default=False, verbose_name='Equipment calibrations checked')),
                ('check_tip', models.BooleanField(default=False, verbose_name='Cone tip check complete')),
                ('check_vis', models.BooleanField(default=False, verbose_name='Visual sieve check complete')),
                ('balance', models.CharField(blank=True, choices=[('BAL-001', 'BAL-001'), ('BAL-003', 'BAL-003'), ('BAL-004', 'BAL-004'), ('BAL-005', 'BAL-005'), ('BAL-006', 'BAL-006'), ('BAL-007', 'BAL-007'), ('BAL-008', 'BAL-008'), ('BAL-009', 'BAL-009'), ('BAL-010', 'BAL-010')], max_length=7, verbose_name='Balance used')),
                ('penetrometer', models.CharField(default='ATT-004', max_length=7)),
                ('test_date', models.DateField(auto_now_add=True)),
                ('preparation_method', models.CharField(blank=True, choices=[('1', 'Natural Condition'), ('2', '>425um removed by hand'), ('3', '>425um removed by washing')], max_length=1, verbose_name='Preparation method')),
                ('oven', models.CharField(blank=True, choices=[('OVE-001', 'OVE-001'), ('OVE-002', 'OVE-002'), ('OVE-004', 'OVE-004'), ('OVE-005', 'OVE-005'), ('OVE-006', 'OVE-006')], max_length=7, verbose_name='Oven used')),
                ('oven_temp', models.IntegerField(blank=True, null=True, verbose_name='Oven temperature (degrees celcius)')),
                ('sieve_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total mass before sieving (grams)')),
                ('sieve_retained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Mass retained on 425um sieve (grams)')),
                ('pl1_con', models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID')),
                ('pl1_con_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)')),
                ('pl1_wet_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)')),
                ('pl1_dry1_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)')),
                ('pl1_dry2_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)')),
                ('pl2_con', models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID')),
                ('pl2_con_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)')),
                ('pl2_wet_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)')),
                ('pl2_dry1_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)')),
                ('pl2_dry2_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)')),
                ('ll1_pene_1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 1 (mm)')),
                ('ll1_pene_2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 2 (mm)')),
                ('ll1_pene_3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 3 (mm)')),
                ('ll1_con', models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID')),
                ('ll1_con_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)')),
                ('ll1_wet_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)')),
                ('ll1_dry1_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)')),
                ('ll1_dry2_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)')),
                ('ll2_pene_1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 1 (mm)')),
                ('ll2_pene_2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 2 (mm)')),
                ('ll2_pene_3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 3 (mm)')),
                ('ll2_con', models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID')),
                ('ll2_con_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)')),
                ('ll2_wet_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)')),
                ('ll2_dry1_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)')),
                ('ll2_dry2_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)')),
                ('ll3_pene_1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 1 (mm)')),
                ('ll3_pene_2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 2 (mm)')),
                ('ll3_pene_3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 3 (mm)')),
                ('ll3_con', models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID')),
                ('ll3_con_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)')),
                ('ll3_wet_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)')),
                ('ll3_dry1_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)')),
                ('ll3_dry2_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)')),
                ('ll4_pene_1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 1 (mm)')),
                ('ll4_pene_2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 2 (mm)')),
                ('ll4_pene_3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 3 (mm)')),
                ('ll4_con', models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID')),
                ('ll4_con_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)')),
                ('ll4_wet_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)')),
                ('ll4_dry1_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)')),
                ('ll4_dry2_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)')),
            ],
        ),
    ]
