# Generated by Django 2.1 on 2018-08-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atterberg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attmodel',
            name='ll1_con',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll1_con_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll1_dry1_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll1_dry2_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll1_pene_1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 1 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll1_pene_2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 2 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll1_pene_3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 3 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll1_wet_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll2_con',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll2_con_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll2_dry1_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll2_dry2_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll2_pene_1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 1 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll2_pene_2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 2 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll2_pene_3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 3 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll2_wet_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll3_con',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll3_con_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll3_dry1_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll3_dry2_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll3_pene_1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 1 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll3_pene_2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 2 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll3_pene_3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 3 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll3_wet_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll4_con',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll4_con_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll4_dry1_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll4_dry2_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll4_pene_1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 1 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll4_pene_2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 2 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll4_pene_3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Penetration 3 (mm)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='ll4_wet_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl1_con',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl1_con_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl1_dry1_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl1_dry2_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl1_wet_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl2_con',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Container ID'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl2_con_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Container mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl2_dry1_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='First dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl2_dry2_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Second dry mass (grams)'),
        ),
        migrations.AlterField(
            model_name='attmodel',
            name='pl2_wet_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wet mass (grams)'),
        ),
    ]
