# Generated by Django 2.1 on 2018-08-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atterberg', '0002_auto_20180822_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attmodel',
            name='identifier',
        ),
        migrations.AddField(
            model_name='attmodel',
            name='depth_top',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Top depth (m)'),
        ),
        migrations.AddField(
            model_name='attmodel',
            name='hole_id',
            field=models.CharField(default='BH01', max_length=8, verbose_name='Hole number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attmodel',
            name='project_id',
            field=models.CharField(default='S180101', max_length=8, verbose_name='Project number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attmodel',
            name='sample_type',
            field=models.CharField(default='B', max_length=4, verbose_name='Sample type'),
            preserve_default=False,
        ),
    ]
